<a href="https://colab.research.google.com/github/wkdtjdwns/Python/blob/main/1.%20%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

파이썬은 띄어쓰기 조심!
print문장은 화면에 출력해주는 명령어

In [ ]:
print('my first python code!')

my first python code!

In [ ]:
name = '장성준'
age = 17
print('안녕하세요 저는' , name, '이고요 나이는' ,age, "입니다.")

안녕하세요 저는 장성준 이고요 나이는 17 입니다.

In [ ]:
# 연산자
a = 5
b = 3
print(a/b) # 나눈 값 (1.6666666666667)

print(a%b) # 나머지 (2)

1.6666666666666667
2

In [ ]:
a = 5
b = 3
print(a == b) # a 랑 b 는 같냐? True / False (False)
print(a != b) # a 랑 b 는 다르냐? True / False (True)

False
True

In [ ]:
a = 5
b = 2
t = b # t = 2
 
b = a # b = a = 5

a = t # a = 2

print(a, b) # 서로 반대가 되게. (2, 5)

2 5

In [ ]:
# a 와 b 만 써서 바꾸기
a = 5
b = 2

a = a + b # a = 5 + 2 = 7
b = a - b # b = 7 - 2 = 5
a = a - b # a = 7 - 5 = 2

print(a, b) # (2, 5) 나오게 하기

2 5

In [ ]:
str = "hello"

In [ ]:
print(str) # 위에 있는 것도 실행시켜야 실행 가능

hello

In [ ]:
# 우리반 학생을 저장 (1 ~ 10번)
# 방법 (1)
s1 = '김개똥'
s2 = '홍길동'
# 만약 학생이 100명이라면 ? => 100개의 변수 필요
# 하나의 묶음으로 보관 => List (다른 언어는 array)

student = ['김개똥', '홍길동', 100] # 리스트에 다른 형태의 자료형도 보관가능 (다른 언어는 안됨)
print(student) # 전체 다 꺼내옴

print(student[0]) # '김개똥' 하나만 꺼내옴 / 리스트는 0 부터 시작 

print(student[2]) # 100 하나만 꺼내옴

student.append('이정환') # .append => 새로운 항목 추가
print(student[3])

student.remove('홍길동') # .remove => 특정 항목 제거 
print(student)

student.pop(1) # .pop => 1번째 항목 제거
print(student)

['김개똥', '홍길동', 100]
김개똥
100
이정환
['김개똥', 100, '이정환']
['김개똥', '이정환']

In [ ]:
# 1번의 이름, 국어, 영어, 정보 성적을 보관
# 2번의 이름, 국어, 영어, 정보 성적을 보관
s1 = ['김개똥', 100, 50, 70]
s2 = ['홍길동', 60, 70 , 100]

cls = [s1, s2] # 리스트 안에 리스트를 넣음 => 2차원 리스트
print(cls) # 2개 다 나옴
print(cls[0][1]) # 김개똥의 국어 점수 100 이 나옴 (0 번지의 1 번 자료)

# 배열과 리스트의 차이점 => 배열은 크기가 고정 =  변경 불가, 리스트는 변경 가능 

# type(변수이름) => 변수의 타입 (자료의 형태를 출력함)
print(type(cls)) # cls 의 자료형

num = 3.14
print(type(num))

[['김개똥', 100, 50, 70], ['홍길동', 60, 70, 100]]
100
<class 'list'>
<class 'float'>

In [ ]:
# 리스트에 관해서.. 문자열 
# String = 문자열
str = 'hello world' # ['h', 'e', 'l' .....] 로 저장되고 있음 -> 리스트처럼 저장됨
print(str[2]) # str 의 3 번째 문자를 출력 
print(len(str)) # len() = 문자의 길이를 출력함

list = [1, 2, 3, 4, 5]
print(len(list)) # 배열의 길이도 출력 가능

l
11
5

In [ ]:
# 반복문 - 반복된 작업을 쉽게
# 상황 - 리스트[0, 0, 0, 0, 0, 0.......] => 100칸 생성
# list = [0, 0, ....... 0] 또는
# list = []  list.append(0) 추가하기 100번

# 반복 명령어 for, while
# for = 제한된 횟수 만큼만 반복
# k = 반복하면서 사용할 변수
# range(범위) = 0 ~ (범위 - 1) 까지 
for k in range(2, 5): # 2 부터 (5 - 1) 까지
# 파이썬은 { } <= 중괄호 대신 들여쓰기(Tab 키) 로 대체 함   
# : = 중괄호 시작과 같은 뜻
  # 안에 들여쓰기를 했음
  print(k)
  print('반복중')

2
반복중
3
반복중
4
반복중

In [ ]:
# 100개의 리스트를 만들고 [0, 2, 4, 6...] 순서로 값을 초기화
# 배열의 항목을 추가하는 명령어 = .append
list = []
i = 0
for k in range(100):
  list.append(i)
  print(list)
  i = i + 2

# java 에서 하는 법
# for(int i = 0 ; i > 200 ; i +2)

[0]
[0, 2]
[0, 2, 4]
[0, 2, 4, 6]
[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8, 10]
[0, 2, 4, 6, 8, 10, 12]
[0, 2, 4, 6, 8, 10, 12, 14]
[0, 2, 4, 6, 8, 10, 12, 14, 16]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192]

In [ ]:
# 또 다른 방법

list = []

#list.append(0)
#list.append(2)
#list.append(4)

#for 변수 in  범위:
# 반복내용
for n in range(0, 200, 2):  #0~200까지 2씩 커짐...  
#for(int i = 0 ; i < 200 ; i = i+2)
  #n = 0 ,1,2,...99
  #list.append(n*2)
  list.append(n)

#... 100번
print(list)
#[0,2,4,6,8....   198]

for k in list:
  print(k)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198]
0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100
102
104
106
108
110
112
114
116
118
120
122
124
126
128
130
132
134
136
138
140
142
144
146
148
150
152
154
156
158
160
162
164
166
168
170
172
174
176
178
180
182
184
186
188
190
192
194
196
198

In [ ]:
# for 는 반복문 => 똑같은 작업을 할 수 있도록 횟수를 지정하는 반복문
# 입력하는 단의 구구단 
# 예) 3 입력 => 3 * 1 = 3 ........... 3 * 9 = 27

n = int(input('숫자를 입력하세요>>>')) # 내가 원하는 숫자 출력
for i in range(1, 10):
  print(f'{n} * {i} = {n*i}') # {} 는 안에 있는 변수의 값을 출력
# print(n, '*', i, '=', n * i ) 도 가능

숫자를 입력하세요>>>3
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27

In [ ]:
# 나머지 연산자의 중요성

# 0. 사용자 입력을 숫자로 받기 
# 1. 1부터 입력수 까지 출력 => for 문 필요
# 2. 3, 6, 9 인지 판단하여 X 로 변환
n = int(input('숫자를 입력해주세요>>> '))

for i in range(1, n+1):
# 3의 배수면 3으로 나누면 나머지가 0
  if i % 3 == 0: # i % 3 == 0: => i 나누기 3 의 나머지가 0 일때 => i 가 3 의 배수일 때 
    print('X', end = ' ')
  else:
    print(i, end = ' ')

숫자를 입력해주세요>>> 10
1 2 X 4 5 X 7 8 X 10

In [ ]:
# OR 연산자

# Java 에서는 OR => ||

n = int(input('숫자를 입력해주세요>>> '))

for i in range(1, n+1):
  # or => 조건식 중에 하나라도 참이면 참
  if i == 3 or i == 6 or i == 9:
    print('X', end = ' ')
  else:
    print(i, end = ' ')

숫자를 입력해주세요>>> 10
1 2 X 4 5 X 7 8 X 10

In [ ]:
# IF 문 복습 FOR 문과 연계
# if = 조건 검사 = 만약 조건식이 참이면 수행할 내용 작성

a = 5
# a 가 5보다 크다면 '큰수' 출력, 아니면 '작은수' 출력
if a > 5: # 콜론(:) 표시 주의
  print('큰수')
  print('입니다.')

### 차이점 -> 들여쓰기를 하지 않아서 print('입니다') 코드가 if문에 들어가지 않음
if a > 5: 
  print('큰수')
print('입니다.')

if a > 5: 
  print('큰수')
else:
  print('작은수')

# else:
#   print('작은수')
if a <= 5:
  print('작은수')

입니다.
작은수
작은수

In [ ]:
# 내가 생각한 숫자 맞추기
# 10번의 기회동안 숫자를 맞춤
# 10번의 기회 => 10번동안 입력을 받음
# 10번 동안 => 10번 반복 => for 문 필요
# 입력받음 => input() 필요
# 내가 입력한 숫자가 맞는지 검사 => if 문 필요
# 10번 반복할 동안 검사를 매번 수행 for 문 안에서 입력, 검사 받기



answer = 15

for i in range(10):
  print("1~100 까지의 숫자 중, 내가 생각한 숫자는?")
  num = int(input(f'{i+1}번째 기회 >>> '))
  if num == answer:
      print('정답입니다!')
      break
  elif num < answer:
    print('UP!')
  elif num > answer:
    print('Down!')

1~100 까지의 숫자 중, 내가 생각한 숫자는?
1번째 기회 >>> 8
UP!
1~100 까지의 숫자 중, 내가 생각한 숫자는?
2번째 기회 >>> 35
Down!
1~100 까지의 숫자 중, 내가 생각한 숫자는?
3번째 기회 >>> 15
정답입니다!

In [ ]:
# 정수 1개를 입력받아 1부터 그 수까지 짝수의 합을 구해보자
# 1 부터 n 까지 반복 => for문
# 반복하면서 나오는 숫자가 짝수 인지 검사 => % 2 == 0
# 합 구하기 => 합을 저장하는 변수 만들기
# 변수를 누적해서 저장하기

num = int(input("아무 숫자나 입력해주세요>>> "))

sum = 0
for i in range(1, num + 1):
  # i 에 1 ~ n 까지의 값이 들어옴
  # i 가 짝수인지 판단
  if i % 2 == 0:
    # sum 에다가 i 를 누적 => sum 에 현재 i 값을 보관
    sum = sum + i

print("1부터 입력한 숫자까지의 짝수의 합계는", sum, "입니다.")

아무 숫자나 입력해주세요>>> 100
1부터 입력한 숫자까지의 짝수의 합계는 2550 입니다.

In [ ]:
# 정수 1개를 입력받아 1부터 그 수까지 홀수의 합을 구해보자
# 1 부터 n 까지 반복 => for문
# 반복하면서 나오는 숫자가 홀수 인지 검사 => % 2 != 0
# 합 구하기 => 합을 저장하는 변수 만들기
# 변수를 누적해서 저장하기


num = int(input("아무 숫자나 입력해주세요>>> "))

sum = 0
for i in range(1, num + 1):
  if i % 2 != 0:
    sum = sum + i

print("1부터 입력한 숫자까지의 홀수의 합계는", sum, "입니다.")

아무 숫자나 입력해주세요>>> 10
1부터 입력한 숫자까지의 홀수의 합계는 25 입니다.

In [ ]:
#가위 = 1 바위 = 2 보 = 3

me = int(input('뭐 낼래? 가위1 바위2 보3'))

com = int(input('뭐 낼래? 가위1 바위2 보3'))

#나의 컴의 비교를 해서 승, 패, 무승부 출력
if me == com:
  print('무승부')

# 내가 이기는 경우
# 나 == 1 그리고 컴 == 3, 나 == 2 그리고 컴 == 1, 나 == 3 그리고 컴 == 2

elif (me - com) % 3 == 1:
  print('승리')

# elif (me - com == -2) or (me - com == 1):
#   print('승리')

# elif (me == 1 and com == 3) or (me == 2 and com == 1) or (me == 3 and com == 2):   
#   print('승리')

else:
  print('패배')

# 내가 지는 경우
# 나 == 1 그리고 컴 == 2, 나 == 2 그리고 컴 == 3, 나 == 3 그리고 컴 == 1
# elif (me == 1 and com == 2) or (me == 2 and com == 3) or (me == 3 and com == 1):
#   print('패배')

In [ ]:
# 1을 입력하면 0 출력
# 0을 입력하면 1 출력

n = input() # 문자열로 입력

# if n == 1 #n 은 문자값이므로   문자 1과 숫자 1은 다름
if n == '1': # 문자 '1'
  print('0') # 문자 0 은 계산 불가능

elif n == '0':
  print('1')

In [ ]:
# 1을 입력하면 0 출력
# 0을 입력하면 1 출력

n = int(input())

print((1 - n))

1
0

In [ ]:
# for 문과 배열을 섞어 보자
# 배열 = 리스트 => 변수의 집합 => 여러개의 변수를 묶어서 보관
# 그럼 어떻게 안에 있는 자료에 접근할 수 있을까? => 주소

lt =[] # 빈 리스트 만들기
# 리스트 관련된 명령어 알기
# lt. => 점을 찍으면 사용할 수 있는 명령어가 나옴
lt.append(1) # 맨 뒤에 추가
lt.append(10)
lt.insert(1, 5) # (번지, 추가할 값)  ,  리스트는 0번지 부터 출발
lt.insert(0, 20) # 번지 수 가 없으면 에러 남

# 1을 삭제

lt.remove(1) # 삭제할때는 주소번지만 이용해서 삭제

print(*lt) # 리스트 이름 앞에 * 를 붙이면 [] 표시  없이 출력 가능

20 5 10

In [ ]:
list = []

for i in range(101):
  list.append(i * 10)

print(list)

In [ ]:
# [0. 10, 20, 30, 40, 50.....1000] 인 배열 만들기

list =[]

for i in range(0, 1001, 10):
  list.append(i)

print(list)

# pos = list.index(40) # 값을 찾아보고 만약 있으면 해당 번지를 pos 변수에 저장

In [ ]:
#리스트에서 index를 쓰지않고 해당 위치 반환

a = [1,2,3,4,5,6,7]  #크기고정
# a에서 쓸수 있는 기능
# pos = a.index(4) => 4의 위치는?
# print(pos) => 3
size = len(a) # a 배열의 길이     /    a.length 는 자바
find = int(input())

#for문을 이용 => a의 길이(크기) 만큼 반복 검사

for i in range(size):
  # a[i] 번지가 find 와 같은가?
  if a[i] == find:
    print(i)
    break

###결과###
# 4입력 =>   3(번지)출력

In [ ]:
# 마지막부터 값 찾기
# hint = range 활용

a = [1,2,3,4,5,6,7,8,9]  #크기고정
size = len(a) 
find = int(input())
# range(5) 0~4까지
# range(1, 5) 1~4까지
# range(1, 10, 2) 1~9까지 2씩 증가
# 10부터 0까지 1씩 감소 => range(11, 0, -1)
for i in range(size, -1, -1):
  if a[i - 1] == (find - 1):
    print(i)
    break

# 더 간편한 방법
a = [1,2,3,4,5,6,7,8,9]  #크기고정
size = len(a) 
find = int(input())

for j in range((size - 1), -1, -1):
  if a[j] == find:
    print(j)
    break

In [ ]:
# for i in range(size):   로 마지막부터 값 찾기

a = [1,2,3,4,5,6,7,8,9]  #크기고정
size = len(a) 
find = int(input())

for i in range(size): 
  # 0 번지 => 9만들기
  pos = (size - 1 - i) # i = 0 일때, 10 - 1 - i => 9 - 0 = 9번지 찾기
  if a[pos] == find:
    print(pos)
    break

In [ ]:
n = [1,2,35,8,56,7,2,5,]

# range(10) => [0,1,2,3,4,5,6,7,8,9]
for i in n: # in 다음에는 range 뿐만 아니라 범위를 가지고 있는 모든 것이 가능함
  print(i)

In [ ]:
n = ['jan','feb','mar','apr','may','june','july']

for i in n: 
  print(i)

In [ ]:
# 반복문

# whlie = ~하는 동안
# 조건식이 참인 동안 반복
k = 0
while k < 5:
  print(k)
  k += 1
print('byebye') 
print(k)

In [ ]:
# 패스워드를 검색하자. 비번이 맞을 때까지 반복

password = '1234'
my = input('비밀번호를 입력해주세요>>> ')

# 비번이 틀렸을 때 반복 => password 와 my 가 같지 않을 때
while my != password: # !는 부정의 의미
  my = input('비밀번호를 입력해주세요>>> ')

print('welcome!')

In [ ]:
pw = '1234'

# 무조건 반복하다가 조건이 맞으면 탈출(break)
# 파이썬에는 do~while문이 없음
# True = 참 / False = 거짓 (대소문자 구분)
while True:
  my = input('비밀번호를 입력해주세요>>> ')
  if my == pw:
    break

In [ ]:
# 문제 1134번

# target = input('찾을 글자를 입력하세요')
# scr = input(문자열을 입력하세요)

target = 'KTX'
src = 'KINTEX'
t_pos = 0
print(target[t_pos]) # 문자열도 리스트로 저장됨

for s in src:
  # KINTEX의 K == KTX[0]인 K 같은지 비교
  if s == target[t_pos]:
    # 만약 글자를 찾으면 target의 다음 글자
    t_pos += 1
    print(s)
    # 글자 수 만큼 다 찾으면 반복문 나오기
    if len(target) == t_pos:
      print('Y')
      break
print('끝')

In [ ]:
for i in range(10, -1, -1):
  print(i)

10
9
8
7
6
5
4
3
2
1
0

In [ ]:
lt = []

for i in range(5):
  lt.append(i)

print(lt)

[0, 1, 2, 3, 4]

In [ ]:
# while 조건: // 조건이 참일 때 기능을 수행함
#   기능

# while 1 > 0:
#     ans = input('Q를 입력하면 종료합니다.')
#     if ans == 'Q':
#       break

ans = ''

while ans != 'Q':
  ans = input('Q를 입력하면 종료합니다')

In [ ]:
# 숫자 하나를 입력받고, 그 숫자부터 1까지 출력, 단 while 이용

n = int(input())

while n > 0:
  print(n)
  n -= 1

In [ ]:
# 숫자를 하나 입력받아서 입력수 ~ 100까지 반복

n = int(input())

while n < 101:
  print(n)
  n += 1

n = int(input())

while True:
  print(n)
  n += 1
  if n == 101:
    break